spring:
  cloud:
    stream:
      bindings:
        input:
          destination: foo
          binder: rabbit1
        output:
          destination: bar
          binder: rabbit2
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                addressess: localhost:5672
        rabbit2:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                addressess: localhost:5672
      rabbit:
        bindings:
          output:
            producer:
              routingKeyExpression: headers['test']